@WordleHelper_ReactWithASP.Server_HostAddress = https://localhost:7105

POST {{WordleHelper_ReactWithASP.Server_HostAddress}}/guess/validate
Content-Type: application/json

{
  "Guess": "beans",
  "PrevGuesses": [
    "wordy",
    "large",
    "ready",
    "hello"
  ]
}

###

POST {{WordleHelper_ReactWithASP.Server_HostAddress}}/guess/possiblewords
Content-Type: application/json

 [
{
    "WordString": "hello",
    "Letters": [
      {
        "Value": "h",
        "correctness": 2
      },
      {
        "Value": "e",
        "correctness": 2
      },
      {
        "Value": "l",
        "correctness": 2
      },
      {
        "Value": "l",
        "correctness": 2
      },
      {
        "Value": "o",
        "correctness": 2
      }
    ]
  }
]

###

# [
#   {
#     "WordString": "hello",
#     "Letters": [
#       {
#         "Value": "h",
#         "LetterCorrectness": 1
#       },
#       {
#         "Value": "e",
#         "LetterCorrectness": 1
#       },
#       {
#         "Value": "l",
#         "LetterCorrectness": 1
#       },
#       {
#         "Value": "l",
#         "LetterCorrectness": 1
#       },
#       {
#         "Value": "0",
#         "LetterCorrectness": 1
#       }
#     ]
#   }
# ]